# Generated by Django 4.0.4 on 2022-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eskort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('imgs', models.TextField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
