# Generated by Django 4.0.4 on 2022-05-09 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('text', tinymce.models.HTMLField(verbose_name='Metin')),
                ('date', models.DateField(auto_now=True, verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='Eskort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefon')),
                ('text', tinymce.models.HTMLField(verbose_name='Açıklama')),
                ('duration', models.DurationField(default=datetime.timedelta(days=7), verbose_name='Süre')),
                ('ilceler', multiselectfield.db.fields.MultiSelectField(choices=[('Aliağa', 'Aliaga'), ('Balçova', 'Balcova'), ('Bayraklı', 'Bayrakli'), ('Bornova', 'Bornova'), ('Buca', 'Buca'), ('Çeşme', 'Cesme'), ('Çiğli', 'Cigli'), ('Gaziemir', 'Gaziemir'), ('Güzelbahçe', 'Guzelbahce'), ('Karabağlar', 'Karabaglar'), ('Karaburun', 'Karaburun'), ('Karşıyaka', 'Karsiyaka'), ('Konak', 'Konak'), ('Menemen', 'Menemen'), ('Narlıdere', 'Narlidere'), ('Seferihisar', 'Seferihisar'), ('Urla', 'Urla')], default='Buca', max_length=200, verbose_name='İlçeler')),
                ('rank', models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')])),
                ('status', models.IntegerField(choices=[(1, 'Acik'), (0, 'Kapali')], default=1, verbose_name='Durum')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('Buca Escort', 'Buca Escort'), ('İzmir Buca Escort', 'Izmir Buca Escort'), ('Buca Escort Bayanlar', 'Buca Escort Bayanlar'), ('Buca Escort Bayan', 'Buca Escort Bayan'), ('Bornova Escort', 'Bornova Escort'), ('İzmir Bornova Escort', 'Izmir Bornova Escort'), ('Alsancak Escort', 'Alsancak Escort'), ('İzmir Alsancak Escort', 'Izmir Alsancak Escort'), ('İzmir Escort', 'Izmir Escort'), ('İzmir Escort Bayanlar', 'Izmir Escort Bayanlar'), ('İzmir Escort Bayan', 'Izmir Escort Bayan'), ('İzmir Escort Kızlar', 'Izmir Escort Kizlar')], max_length=50, verbose_name='Keyword')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='sayfa.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='esc-img')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sayfa.eskort')),
            ],
        ),
    ]
