# Generated by Django 4.0.4 on 2022-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskort',
            name='imgs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')]),
        ),
    ]
