# Generated by Django 4.0.4 on 2022-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0002_alter_eskort_imgs_alter_eskort_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskort',
            name='img1',
            field=models.ImageField(null=True, upload_to='esc-img/'),
        ),
        migrations.AddField(
            model_name='eskort',
            name='img2',
            field=models.ImageField(null=True, upload_to='esc-img/'),
        ),
        migrations.AddField(
            model_name='eskort',
            name='img3',
            field=models.ImageField(null=True, upload_to='esc-img/'),
        ),
        migrations.AddField(
            model_name='eskort',
            name='status',
            field=models.IntegerField(choices=[(1, 'Acik'), (0, 'Kapali')], default=0),
        ),
    ]
