# Generated by Django 4.0.4 on 2022-05-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0002_alter_keyword_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog-img', verbose_name='Resim')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfa.blog', verbose_name='images')),
            ],
        ),
    ]
