# Generated by Django 4.0.4 on 2022-05-03 18:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0003_eskort_img1_eskort_img2_eskort_img3_eskort_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskort',
            name='ilceler',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Aliağa', 'Aliaga'), ('Balçova', 'Balcova'), ('Bayraklı', 'Bayrakli'), ('Bornova', 'Bornova'), ('Buca', 'Buca'), ('Çeşme', 'Cesme'), ('Çiğli', 'Cigli'), ('Gaziemir', 'Gaziemir'), ('Güzelbahçe', 'Guzelbahce'), ('Karabağlar', 'Karabaglar'), ('Karaburun', 'Karaburun'), ('Karşıyaka', 'Karsiyaka'), ('Konak', 'Konak'), ('Menemen', 'Menemen'), ('Narlıdere', 'Narlidere'), ('Seferihisar', 'Seferihisar'), ('Urla', 'Urla')], default=('buca', 'Buca'), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eskort',
            name='imgs',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='esc-img')),
                ('esc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayfa.eskort')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
