# Generated by Django 4.0.4 on 2022-05-03 18:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0004_eskort_ilceler_alter_eskort_imgs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskort',
            name='ilceler',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Aliağa', 'Aliaga'), ('Balçova', 'Balcova'), ('Bayraklı', 'Bayrakli'), ('Bornova', 'Bornova'), ('Buca', 'Buca'), ('Çeşme', 'Cesme'), ('Çiğli', 'Cigli'), ('Gaziemir', 'Gaziemir'), ('Güzelbahçe', 'Guzelbahce'), ('Karabağlar', 'Karabaglar'), ('Karaburun', 'Karaburun'), ('Karşıyaka', 'Karsiyaka'), ('Konak', 'Konak'), ('Menemen', 'Menemen'), ('Narlıdere', 'Narlidere'), ('Seferihisar', 'Seferihisar'), ('Urla', 'Urla')], default='Buca', max_length=200),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='imgs',
            field=models.JSONField(default=0),
        ),
    ]
