# Generated by Django 4.0.4 on 2022-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0005_alter_eskort_ilceler_alter_eskort_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eskort',
            name='imgs',
        ),
        migrations.AddField(
            model_name='eskort',
            name='images',
            field=models.JSONField(default={}),
        ),
    ]
