# Generated by Django 4.0.4 on 2022-05-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0008_alter_eskort_name_alter_image_esc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eskort',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='eskort',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='eskort',
            name='img3',
        ),
    ]
