# Generated by Django 4.0.4 on 2022-05-04 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0009_remove_eskort_img1_remove_eskort_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AddField(
            model_name='eskort',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7), verbose_name='Süre'),
        ),
    ]
