# Generated by Django 4.0.4 on 2022-05-05 23:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0010_alter_image_options_eskort_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskort',
            name='ilceler',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Aliağa', 'Aliaga'), ('Balçova', 'Balcova'), ('Bayraklı', 'Bayrakli'), ('Bornova', 'Bornova'), ('Buca', 'Buca'), ('Çeşme', 'Cesme'), ('Çiğli', 'Cigli'), ('Gaziemir', 'Gaziemir'), ('Güzelbahçe', 'Guzelbahce'), ('Karabağlar', 'Karabaglar'), ('Karaburun', 'Karaburun'), ('Karşıyaka', 'Karsiyaka'), ('Konak', 'Konak'), ('Menemen', 'Menemen'), ('Narlıdere', 'Narlidere'), ('Seferihisar', 'Seferihisar'), ('Urla', 'Urla')], default='Buca', max_length=200, verbose_name='İlçeler'),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='status',
            field=models.IntegerField(choices=[(1, 'Acik'), (0, 'Kapali')], default=0, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='text',
            field=models.TextField(verbose_name='Açıklama'),
        ),
    ]
