# Generated by Django 4.0.4 on 2022-05-06 11:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfa', '0011_alter_eskort_ilceler_alter_eskort_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskort',
            name='status',
            field=models.IntegerField(choices=[(1, 'Acik'), (0, 'Kapali')], default=1, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='eskort',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Açıklama'),
        ),
    ]
